openapi: 3.0.2
info:
  title: FastAPI
  version: 0.1.0
paths:
  "/":
    get:
      summary: Health Check
      description: health check
      operationId: health_check__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HealthCheckResponse"
  "/room/list/{user_id}":
    get:
      tags:
        - room
      summary: Get Room List
      description: 채팅방 리스트 조회
      operationId: get_room_list_room_list__user_id__get
      parameters:
        - required: true
          schema:
            title: User Id
            type: string
          name: user_id
          in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Response Get Room List Room List  User Id  Get
                type: array
                items: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/room/create":
    post:
      tags:
        - room
      summary: Create Room
      description: 채팅방 생성 -> 유저별 채팅방 리스트 추가 -> 채팅방 리턴
      operationId: create_room_room_create_post
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/RoomCreateRequest"
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Response Create Room Room Create Post
                type: string
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/room/message/{room_id}":
    get:
      tags:
        - room
      summary: Messages
      description: 채팅방 메세지 조회
      operationId: messages_room_message__room_id__get
      parameters:
        - required: true
          schema:
            title: Room Id
            type: string
          name: room_id
          in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Response Messages Room Message  Room Id  Get
                type: array
                items: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/chat/online/{user_id}":
    post:
      tags:
        - chat
      summary: Online
      description: 온라인 상태로 변경
      operationId: online_chat_online__user_id__post
      parameters:
        - required: true
          schema:
            title: User Id
            type: string
          name: user_id
          in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/chat/offline/{user_id}":
    delete:
      tags:
        - chat
      summary: Offline
      description: 오프라인 상태로 변경
      operationId: offline_chat_offline__user_id__delete
      parameters:
        - required: true
          schema:
            title: User Id
            type: string
          name: user_id
          in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/chat":
    get:
      tags:
        - chat
      summary: Get
      operationId: get_chat_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
components:
  schemas:
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            "$ref": "#/components/schemas/ValidationError"
    HealthCheckResponse:
      title: HealthCheckResponse
      required:
        - message
      type: object
      properties:
        message:
          title: Message
          type: string
    RoomCreateRequest:
      title: RoomCreateRequest
      required:
        - user_id
        - target_id
      type: object
      properties:
        user_id:
          title: User Id
          type: string
        target_id:
          title: Target Id
          type: string
    ValidationError:
      title: ValidationError
      required:
        - loc
        - msg
        - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
              - type: string
              - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string