version: "3.9"

# 실행 docker-compose up --build
# 실행 + daemonize docker-compose up --build -d
# 도커 종료하기 docker-compose [down / stop]

services:
  chat-web:
    container_name: chat-web
    build:
      context: nginx/
      dockerfile: .
    ports:
      - "19000:9000"
      - "19001:9001"
    depends_on:
      - chat-api
      - chat-message

  chat-api:
    container_name: chat-api
    build:
      context: .
      dockerfile: dockerfile.api
    volumes:
      - .:/code

  chat-message:
    container_name: chat-message
    build:
      context: .
      dockerfile: dockerfile.message
    volumes:
      - .:/code
