FROM python:3.9

COPY . /code
WORKDIR /code

RUN pip install -r requirements.txt

EXPOSE "9000"
CMD ["gunicorn", "-k", "uvicorn.workers.UvicornWorker", "server.api.main:app", "--bind", "0.0.0.0:9000"]