FROM python:3.9

WORKDIR /code
COPY . /code

RUN pip install -r requirements.txt

EXPOSE "9001"
CMD ["gunicorn", "-k", "uvicorn.workers.UvicornWorker", "server.message.main:app", "--bind", "0.0.0.0:9001"]