# Test your FastAPI endpoints

### health check
GET http://localhost
Accept: application/json

### get lists
GET http://localhost/room/list/1
Accept: application/json

### get message
GET http://localhost/room/message/1:2
Accept: application/json