openapi: 3.0.2
info:
  title: ChatPlatform openapi
  version: '1'
paths:
  "/":
    get:
      summary: Health Check
      description: health check
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HealthCheckResponse"

  "/users":
    post:
      summary: Registration user data
      description: |
        다음과 같은 호출 시점에 필요
        1. 최초 회원가입 시
        2. 유저 정보 수정 시
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/UserRequest"
      responses:
        '200':
          description: ID와 같이 반환
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UserResponse"

  "/users/{service}/{user_id}/token":
    post:
      summary: Add a user device token
      description: |
        유저 디바이스 토큰 추가
      parameters:
        - required: true
          schema:
            title: Service from
            type: string
            enum: [PICKME, DIJKSTRA]
          name: service
          in: path
        - required: true
          schema:
            title: User Id
            type: string
          name: user_id
          in: path
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/UserDeviceToken"
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/UserDeviceToken"

  "/channels/{service}/{user_id}":
    get:
      summary: Return channel list
      description: 채팅방 목록
      parameters:
        - required: true
          schema:
            title: Service from
            type: string
            enum: [PICKME, DIJKSTRA]
          name: service
          in: path
        - required: true
          schema:
            title: User Id
            type: string
          name: user_id
          in: path
      responses:
        '200':
          description: 방목록
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ChannelList"

  "/channels":
    post:
      summary: Create channel
      description: 채팅방 생성
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                members:
                  type: array
                  items:
                    type: object
                    properties:
                      service:
                        type: string
                      user_id:
                        type: string
                type:
                  type: string
                  enum: [1_ON_1, GROUP]
      responses:
        '200':
          description: 채팅방 URL
          content:
            application/json:
              schema:
                type: object
                properties:
                  channel:
                    type: string

  "/channels/{channel}/messages":
    get:
      summary: Return channel conversations
      description: 채팅 내역 조회
      parameters:
        - required: true
          schema:
            title: channel url
            type: string
          name: channel
          in: path
      responses:
        '200':
          description: 채팅 내역
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Message"

  "/chat/{service}/{user_id}":
    get:
      summary: ws protocol
      description: 웹소켓 프로토콜을 통해 사용
      parameters:
        - required: true
          schema:
            title: Service from
            type: string
            enum: [PICKME, DIJKSTRA]
          name: service
          in: path
        - required: true
          schema:
            title: User Id
            type: string
          name: user_id
          in: path
      responses:
        '200':
          description: websocket


components:
  schemas:
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            "$ref": "#/components/schemas/ValidationError"
    HealthCheckResponse:
      title: HealthCheckResponse
      required:
        - message
      type: object
      properties:
        message:
          title: Message
          type: string
    UserRequest:
      title: User Request
      required:
        - service
        - user_id
        - nickname
      type: object
      properties:
        service:
          type: string
          enum: [PICKME, DIJKSTRA]
        user_id:
          type: string
        nickname:
          type: string
        _meta:
          type: object
    UserResponse:
      title: User Response
      type: object
      properties:
        service:
          type: string
          enum: [PICKME, DIJKSTRA]
        user_id:
          type: string
        nickname:
          type: string
        last_seen_at:
          type: integer
        _meta:
          type: object
    UserDeviceToken:
      title: User Device Token
      required:
        - service
        - user_id
        - token_type
      type: object
      properties:
        service:
          type: string
          enum: [PICKME, DIJKSTRA]
        user_id:
          type: string
        token_type:
          type: string
          enum: [fcm, apns]
        fcm_device_token:
          type: string
        apns_device_token:
          type: string
    ChannelList:
      title: ChannelList
      type: array
      items:
        type: object
        properties:
          channel:
            type: string
          type:
            type: string
            enum: [1_ON_1, GROUP]
          member_count:
            type: integer
          members:
            type: array
            items:
              "$ref": "#/components/schemas/UserResponse"
          unread_message_count:
            type: integer
          last_message:
            "$ref": "#/components/schemas/Message"
          _meta:
            type: object
    Message:
      title: Message
      type: object
      properties:
        message_id:
          type: string
        type:
          type: string
          enum: [PLAINTEXT, PLACE, MEDIA]
        message:
          type: string
        place:
          type: object
          properties:
            coordinate:
              type: object
            place_info:
              type: object
        _meta:
          type: object
    RoomCreateRequest:
      title: RoomCreateRequest
      required:
        - user_id
        - target_id
      type: object
      properties:
        user_id:
          title: User Id
          type: string
        target_id:
          title: Target Id
          type: string
    ValidationError:
      title: ValidationError
      required:
        - loc
        - msg
        - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
              - type: string
              - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string