openapi: 3.0.2
info:
  title: ChatPlatform openapi
  version: 0.2.0
paths:
  "/":
    get:
      summary: Health Check
      description: health check
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HealthCheckResponse"
  # action
  # POST 1 GET  PUT DELETE
  # /users
  # /users/{id}
  # post put
  "/users/_bulk":
    post:
      summary: dd
      description: dd
      responses:
        '200':
          description: Bulk use

  "/rooms":
    put:
      summary: 방생성
      description: dd
      responses:
        '200':
          description: 방생성

  "/conversations":
    put:
      summary: 메세지
      description: dd
      responses:
        '200':
          description: 방생성

  "/websocket":
    put:
      summary: 메세지
      description: dd
      responses:
        '200':
          description: 방생성

components:
  schemas:
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            "$ref": "#/components/schemas/ValidationError"
    HealthCheckResponse:
      title: HealthCheckResponse
      required:
        - message
      type: object
      properties:
        message:
          title: Message
          type: string